/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { interactionTypeSchema } from '../../models/interactionType.js';
import { optional, string, typedExpandoObject, unknown } from '../../schema.js';

export const customerInfoMetadataRequestSchema = typedExpandoObject(
  {
    version: ['version', string()],
    providerId: ['providerId', string()],
    xAkoyaInteractionType: [
      'x-akoya-interaction-type',
      optional(interactionTypeSchema),
    ],
  },
  'additionalProperties',
  optional(unknown())
);

export const getAccountHolderMetadataRequestSchema = typedExpandoObject(
  {
    accountId: ['accountId', string()],
    version: ['version', string()],
    providerId: ['providerId', string()],
    xAkoyaInteractionType: [
      'x-akoya-interaction-type',
      optional(interactionTypeSchema),
    ],
  },
  'additionalProperties',
  optional(unknown())
);

