/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { optional, string, typedExpandoObject, unknown } from '../../schema.js';

export const requestTokenMetadataRequestSchema = typedExpandoObject(
  {
    authorization: ['Authorization', string()],
    code: ['code', string()],
    redirectUri: ['redirect_uri', string()],
  },
  'additionalProperties',
  optional(unknown())
);

export const refreshTokenMetadataRequestSchema = typedExpandoObject(
  {
    refreshToken: ['refresh_token', string()],
    clientId: ['client_id', string()],
    clientSecret: ['client_secret', string()],
  },
  'additionalProperties',
  optional(unknown())
);

export const revokeTokenMetadataRequestSchema = typedExpandoObject(
  {
    refreshToken: ['refresh_token', string()],
    clientId: ['client_id', string()],
    clientSecret: ['client_secret', string()],
  },
  'additionalProperties',
  optional(unknown())
);

