/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { acceptSchema } from '../../models/accept.js';
import { interactionTypeSchema } from '../../models/interactionType.js';
import {
  number,
  optional,
  string,
  typedExpandoObject,
  unknown,
} from '../../schema.js';

export const getStatementListMetadataRequestSchema = typedExpandoObject(
  {
    accountId: ['accountId', string()],
    version: ['version', string()],
    providerId: ['providerId', string()],
    startTime: ['startTime', optional(string())],
    endTime: ['endTime', optional(string())],
    offset: ['offset', optional(string())],
    limit: ['limit', optional(number())],
    xAkoyaInteractionType: [
      'x-akoya-interaction-type',
      optional(interactionTypeSchema),
    ],
  },
  'additionalProperties',
  optional(unknown())
);

export const getStatementsMetadataRequestSchema = typedExpandoObject(
  {
    accountId: ['accountId', string()],
    version: ['version', string()],
    providerId: ['providerId', string()],
    statementId: ['statementId', string()],
    accept: ['Accept', optional(acceptSchema)],
    xAkoyaInteractionType: [
      'x-akoya-interaction-type',
      optional(interactionTypeSchema),
    ],
  },
  'additionalProperties',
  optional(unknown())
);

