/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { interactionTypeSchema } from '../../models/interactionType.js';
import { mediaTypeSchema } from '../../models/mediaType.js';
import { typeDataTypeSchema } from '../../models/typeDataType.js';
import { typeFormTypeSchema } from '../../models/typeFormType.js';
import { versionSchema } from '../../models/version.js';
import {
  array,
  optional,
  string,
  typedExpandoObject,
  unknown,
} from '../../schema.js';

export const taxFormsSearchMetadataRequestSchema = typedExpandoObject(
  {
    version: ['version', versionSchema],
    providerId: ['providerId', string()],
    xAkoyaInteractionId: ['x-akoya-interaction-id', optional(string())],
    xAkoyaInteractionType: [
      'x-akoya-interaction-type',
      optional(interactionTypeSchema),
    ],
    accept: ['Accept', optional(array(mediaTypeSchema))],
    taxYear: ['taxYear', optional(string())],
    taxForms: ['taxForms', optional(array(typeFormTypeSchema))],
    accountId: ['accountId', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);

export const getTaxFormMetadataRequestSchema = typedExpandoObject(
  {
    version: ['version', versionSchema],
    providerId: ['providerId', string()],
    taxFormId: ['taxFormId', string()],
    xAkoyaInteractionId: ['x-akoya-interaction-id', optional(string())],
    xAkoyaInteractionType: [
      'x-akoya-interaction-type',
      optional(interactionTypeSchema),
    ],
    taxDataType: ['taxDataType', optional(typeDataTypeSchema)],
    accept: ['Accept', optional(array(mediaTypeSchema))],
  },
  'additionalProperties',
  optional(unknown())
);

