/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { DepositBalances, depositBalancesSchema } from './depositBalances.js';

export interface DepositBalance {
  /** Data elements included with balances specific to deposit accounts */
  depositAccount?: DepositBalances;
  additionalProperties?: Record<string, unknown>;
}

export const depositBalanceSchema: Schema<DepositBalance> = typedExpandoObject(
  {
    depositAccount: [
      'depositAccount',
      optional(lazy(() => depositBalancesSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
