/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  InsuranceBalances,
  insuranceBalancesSchema,
} from './insuranceBalances.js';

export interface InsuranceBalanceInfo {
  /** Data elements included with balances specific to insurance accounts */
  insuranceAccount?: InsuranceBalances;
  additionalProperties?: Record<string, unknown>;
}

export const insuranceBalanceInfoSchema: Schema<InsuranceBalanceInfo> = typedExpandoObject(
  {
    insuranceAccount: [
      'insuranceAccount',
      optional(lazy(() => insuranceBalancesSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
