/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  InvestmentAccountWithAllDetails,
  investmentAccountWithAllDetailsSchema,
} from './investmentAccountWithAllDetails.js';

export interface InvestmentBalanceInfo {
  /** Data elements included with the investment product */
  investmentAccount?: InvestmentAccountWithAllDetails;
  additionalProperties?: Record<string, unknown>;
}

export const investmentBalanceInfoSchema: Schema<InvestmentBalanceInfo> = typedExpandoObject(
  {
    investmentAccount: [
      'investmentAccount',
      optional(lazy(() => investmentAccountWithAllDetailsSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
