/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Links, linksSchema } from './links.js';

export interface PaginatedArray {
  links?: Links;
  additionalProperties?: Record<string, unknown>;
}

export const paginatedArraySchema: Schema<PaginatedArray> = typedExpandoObject(
  { links: ['links', optional(lazy(() => linksSchema))] },
  'additionalProperties',
  optional(unknown())
);
