/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { interactionTypeSchema } from '../../models/interactionType.js';
import { modeSchema } from '../../models/mode.js';
import { optional, string, typedExpandoObject, unknown } from '../../schema.js';

export const getAccountsMetadataRequestSchema = typedExpandoObject(
  {
    version: ['version', string()],
    providerId: ['providerId', string()],
    xAkoyaInteractionType: [
      'x-akoya-interaction-type',
      optional(interactionTypeSchema),
    ],
    mode: ['mode', optional(modeSchema)],
    accountIds: ['accountIds', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);

export const getTaxlotsMetadataRequestSchema = typedExpandoObject(
  {
    version: ['version', string()],
    providerId: ['providerId', string()],
    accountId: ['accountId', string()],
    holdingId: ['holdingId', string()],
    xAkoyaInteractionType: [
      'x-akoya-interaction-type',
      optional(interactionTypeSchema),
    ],
    offset: ['offset', optional(string())],
    limit: ['limit', optional(string())],
    accountIds: ['accountIds', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);

