/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { interactionTypeSchema } from '../../models/interactionType.js';
import { modeSchema } from '../../models/mode.js';
import {
  number,
  optional,
  string,
  typedExpandoObject,
  unknown,
} from '../../schema.js';

export const getTransactionsMetadataRequestSchema = typedExpandoObject(
  {
    version: ['version', string()],
    providerId: ['providerId', string()],
    accountId: ['accountId', string()],
    startTime: ['startTime', optional(string())],
    endTime: ['endTime', optional(string())],
    offset: ['offset', optional(string())],
    limit: ['limit', optional(number())],
    xAkoyaInteractionType: [
      'x-akoya-interaction-type',
      optional(interactionTypeSchema),
    ],
    mode: ['mode', optional(modeSchema)],
  },
  'additionalProperties',
  optional(unknown())
);

