/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  InvestmentBalances,
  investmentBalancesSchema,
} from './investmentBalances.js';

export interface InvestmentBalance {
  /** Data elements included with balances specific to investment accounts */
  investmentAccount?: InvestmentBalances;
  additionalProperties?: Record<string, unknown>;
}

export const investmentBalanceSchema: Schema<InvestmentBalance> = typedExpandoObject(
  {
    investmentAccount: [
      'investmentAccount',
      optional(lazy(() => investmentBalancesSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
