/**
 * Akoya
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  MonthAbbreviation,
  monthAbbreviationSchema,
} from './monthAbbreviation.js';

/** Month and amount pair used on IRS Form 1099-K, etc. */
export interface MonthAndAmount {
  /** Month */
  month?: MonthAbbreviation;
  /** Amount */
  amount?: number;
  additionalProperties?: Record<string, unknown>;
}

export const monthAndAmountSchema: Schema<MonthAndAmount> = typedExpandoObject(
  {
    month: ['month', optional(monthAbbreviationSchema)],
    amount: ['amount', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
